### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by sappi13** [PortSwigger/http-request-smuggler#55] opened 2022-10-20 23:56 UTC
If I select launch all scans, I am not able to see "Ok" button. I am using Macbook Pro 2015 model.
<img width="958" alt="Screenshot 2022-10-20 at 7 55 15 PM" src="https://user-images.githubusercontent.com/7771468/197080807-5cf1caa9-838f-4f9d-9c63-ff4c2b2aacfd.png">

**Comment by albinowax** [comment] 2022-10-21 07:06
For now, you can submit using ctrl+enter

**Comment by albinowax** [comment] 2022-10-21 07:07
This is a duplicate of #34

**Closed by albinowax** 2022-10-21 07:07 UTC
